#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check
    methods: ['POST']
api_me:
    path: /me
    methods: [GET]
    defaults: { _controller: AppBundle:Me:get }